// ─── Manufacturer & Product Data ─────────────────────────────────────────────

// 44060 (Mentor, OH) regional note: Northeast Ohio — Lake County, hail-prone,
// heavy lake-effect snow, freeze-thaw cycles. Colors marked "Popular in 44060"
// are regional bestsellers for Northeast Ohio homes.

export const MANUFACTURERS = [
  // ─── CERTAINTEED ──────────────────────────────────────────────────────────
  {
    slug: "certainteed",
    name: "CertainTeed",
    tagline: "Quality. Confidence. Craftsmanship.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/CertainTeed_logo.svg/320px-CertainTeed_logo.svg.png",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/e9a7b92ee_generated_image.png",
    description:
      "CertainTeed has been a North American leader in building products for over 110 years. Their roofing and siding lines are trusted by contractors and homeowners alike for unmatched durability, aesthetic choice, and industry-leading warranties.",
    website: "https://www.certainteed.com",
    categories: [
      {
        slug: "roofing",
        label: "Roofing",
        description: "CertainTeed's asphalt shingle lines offer beauty, performance, and class-leading warranties backed by the Integrity Roof System.",
        products: [
          {
            slug: "landmark",
            name: "Landmark",
            tagline: "The #1 selling shingle in North America.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/75285b1c5_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Architectural / Laminate",
            colors: "Over 30 color options",
            colorList: [
              { name: "Weathered Wood", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/ldn4f3lswm/jpeg/landmark-wewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Charcoal Black", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/u9mzpbfyso/jpeg/landmark-chbl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Colonial Slate", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/7rzafrqpkc/jpeg/landmark-cosl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Heather Blend", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/ea6xibbsvi/jpeg/landmark-hebl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Burnt Sienna", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/kacqyi6f4s/jpeg/landmark-busi-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Georgetown Gray", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/vuv1nqq9xn/jpeg/landmark-gegr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Pewterwood", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/jdwnz8ncgd/jpeg/landmark-pewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Pewter", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/ooqbpptwwt/jpeg/landmark-pewt-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Thunderstorm Gray", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/jtvjmd0zge/jpeg/landmark-thgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Moire Black", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/u5payeweli/jpeg/landmark-mobl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Driftwood", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/bultqbanif/jpeg/landmark-drif-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Cobblestone Gray", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/jdmcozucet/jpeg/landmark-cogr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Silver Birch", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/0ee0lfqiph/jpeg/landmark-sibi-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Granite Gray", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/a89kcig6oz/jpeg/landmark-grgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
            ],
            description:
              "The CertainTeed Landmark shingle is the best-selling shingle in North America for good reason — it combines a timeless dimensional look with exceptional performance. Featuring StreakFighter® algae-resistance technology and a fiberglass mat base, Landmark delivers lasting beauty with minimal maintenance.",
            features: [
              "StreakFighter® algae-resistance with 10-year warranty",
              "Maximum Wind Resistance Option available (130 mph)",
              "SureStart™ PLUS protection for first 10 years",
              "Dual-layer construction for dimensional depth",
              "Available in over 30 colors to match any home",
              "Compatible with the full Integrity Roof System",
              "Class A fire rating",
              "Energy Star rated options available",
            ],
            idealFor: "Homeowners wanting a classic, proven architectural shingle with excellent value.",
          },
          {
            slug: "landmark-pro",
            name: "Landmark PRO",
            tagline: "Enhanced beauty with even more depth.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/75285b1c5_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Architectural / Enhanced Laminate",
            colors: "Over 35 color options",
            colorList: [
              { name: "Max Def Weathered Wood", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/xibppkws4f/jpeg/landmarkpro-mdwewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Charcoal Black", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/48wrdebddn/jpeg/landmarkpro-mdchbl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Colonial Slate", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/5rbngo6wv2/jpeg/landmarkpro-mdcosl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Georgetown Gray", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/9tepukr60v/jpeg/landmarkpro-mdgegr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Heather Blend", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/shwhl8fdov/jpeg/landmarkpremium-mdhebl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Burnt Sienna", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/xxyljnow9x/jpeg/landmarkpro-mdbusi-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Cobblestone Gray", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/fsgccirwwb/jpeg/landmarkpro-mdcogr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Driftwood", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/9a4dub21u2/jpeg/landmarkpro-mddrif-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Granite Gray", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/zmceubuox7/jpeg/landmarkpro-mdgrgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Pewter", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/vuczoxd3b2/jpeg/landmarkpro-mdpewt-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Moire Black", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/g8godmur93/jpeg/landmarkpro-mdmobl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Max Def Pewterwood", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/zlzc8lf8oc/jpeg/landmarkpro-mdpewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
            ],
            description:
              "The Landmark PRO builds on the best-selling Landmark platform with an even richer, deeper profile. Its triple-layer construction creates a more dramatic shadow effect, giving homes a premium aesthetic that rivals more expensive wood shake or slate options.",
            features: [
              "Triple-layer construction for maximum shadow depth",
              "StreakFighter® algae-resistance standard",
              "SureStart™ PLUS 10-year labor warranty",
              "Over 35 designer colors",
              "Compatible with Integrity Roof System",
              "Lifetime manufacturer warranty",
              "Class A fire rating",
            ],
            idealFor: "Homeowners who want more visual impact than a standard architectural shingle.",
          },
          {
            slug: "belmont",
            name: "Belmont®",
            tagline: "Slate-inspired luxury at an accessible price point.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/ecfea251b_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph (upgradable to 130 mph)",
            style: "Premium Laminate / Slate Look",
            colors: "12 curated color blends",
            colorList: [
              { name: "Black Granite", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/taab9njc0x/jpeg/belmont-blgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Colonial Slate", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/hfps19fe4s/jpeg/belmont-cosl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Shenandoah", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/xh0mgomnpv/jpeg/belmont-shen-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Stonegate Gray", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/otfvocuybe/jpeg/belmont-stgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Weathered Wood", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/mijbq44uoa/jpeg/belmont-wewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
            ],
            description:
              "The CertainTeed Belmont is a triple-layered, built-up luxury shingle with an 8\" exposure designed to simulate the look of slate at a more accessible price point than the Grand Manor.",
            features: [
              "Triple-layer construction for authentic slate depth",
              "8\" exposure for dramatic shadow effect",
              "StreakFighter® 30-year algae resistance warranty",
              "110 mph wind warranty (upgradable to 130 mph)",
              "Lifetime Limited transferable warranty",
              "Class A fire rating",
            ],
            idealFor: "Homeowners wanting a slate aesthetic with strong warranty coverage.",
          },
          {
            slug: "grand-manor",
            name: "Grand Manor®",
            tagline: "The most authentic slate-look shingle CertainTeed makes.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/7ecade1a0_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Ultra-Premium / Natural Slate Look",
            colors: "10 rich color blends",
            colorList: [
              { name: "Colonial Slate", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/hgsd2zt2rh/jpeg/grandmanor-cosl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Stonegate Gray", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/iazwy2ak91/jpeg/grandmanor-stgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Black Pearl", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/o6j87iy2fu/jpeg/grandmanor-blpe-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Weathered Wood", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/xss5lzes6l/jpeg/grandmanor-wewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Gatehouse Slate", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/erfcy6glkq/jpeg/grandmanor-gasl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Brownstone", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/y7oy60mftm/jpeg/grandmanor-brown-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Chestnut", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/qwktpvkp7s/jpeg/grandmanor-ches-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Georgian Brick", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/weoweilmhg/jpeg/grandmanor-gebr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Sherwood Forest", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/lupukwlioh/jpeg/grandmanor-shfo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
            ],
            description:
              "The Grand Manor® is CertainTeed's flagship luxury shingle — a heavyweight, multi-layer laminate that delivers the most convincing slate appearance available in an asphalt product.",
            features: [
              "Heavyweight multi-layer construction for maximum depth",
              "Distinctive random-cut edge mimicking natural slate",
              "UL 2218 Class 4 impact resistance",
              "StreakFighter® algae resistance",
              "Lifetime Limited warranty",
              "Class A fire rating",
            ],
            idealFor: "Premium and historic homes where the most authentic, dramatic slate appearance is the top priority.",
          },
          {
            slug: "presidential-shake",
            name: "Presidential® Shake®",
            tagline: "The original premium cedar shake look in an asphalt shingle.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/cb9347816_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph (upgradable)",
            style: "Ultra-Premium / Cedar Shake Look",
            colors: "10 natural color blends",
            colorList: [
              { name: "Weathered Wood", tier: "standard", popular: true, swatchUrl: "https://certainteed.widen.net/content/9s9q2glcwi/jpeg/presidential-wewo-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Charcoal Black", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/xng1oqchkf/jpeg/presidential-chbl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Shadow Gray", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/7jaggzbe8c/jpeg/presidential-shgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Country Gray", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/ptik6uq2so/jpeg/presidential-ctrgr-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Autumn Blend", tier: "standard", popular: false, swatchUrl: "https://certainteed.widen.net/content/9sg7axj067/jpeg/presidential-aubl-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
              { name: "Aged Bark", tier: "premium", popular: false, swatchUrl: "https://certainteed.widen.net/content/fnkabhjluk/jpeg/presidential-agba-swatch.jpeg?crop=yes&k=c&w=120&h=120" },
            ],
            description:
              "The Presidential® Shake® is CertainTeed's benchmark cedar shake-look shingle — a multi-layer laminate designed to replicate the depth, texture, and natural variation of real hand-split cedar shake.",
            features: [
              "Multi-layer laminate ~350 lbs per square",
              "Realistic cedar shake texture and varied exposure",
              "StreakFighter® 15-year algae resistance",
              "SureStart™ PLUS 10-year labor warranty",
              "Lifetime Limited transferable warranty",
              "Class A fire rating (unlike real cedar)",
            ],
            idealFor: "Homeowners who want the timeless look of real cedar shake with the safety and durability of asphalt.",
          },
        ],
      },
      {
        slug: "siding",
        label: "Siding",
        description: "CertainTeed vinyl and fiber cement siding lines deliver outstanding curb appeal, weather performance, and long-term value.",
        products: [
          {
            slug: "monogram",
            name: "Monogram (.046)",
            tagline: "Premium vinyl siding with exclusive features.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/69018a151_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Double 4\" Dutch Lap / Clapboard",
            colors: "Over 50 colors",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Linen", tier: "standard", popular: true },
              { name: "Antique White", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Autumn Tan", tier: "standard", popular: false },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Pewter", tier: "standard", popular: false },
              { name: "Heathered Moss", tier: "premium", popular: false },
              { name: "Midnight Blue", tier: "premium", popular: false },
              { name: "Chestnut", tier: "premium", popular: false },
            ],
            description:
              "Monogram is CertainTeed's flagship vinyl siding system (.046\"), featuring TripleLock® installation technology that locks panels at three points for unmatched weather resistance.",
            features: [
              "TripleLock® three-point locking system",
              "WeatherMax™ UV protection to prevent fading",
              "110 mph wind warranty",
              "Lifetime color warranty",
              "Available in 50+ colors",
            ],
            idealFor: "Homeowners wanting a lifetime, no-maintenance siding with maximum wind protection.",
          },
          {
            slug: "mainstreet",
            name: "Mainstreet (.042)",
            tagline: "Mid-range performance with a broad color palette.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/fca27f5be_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "100 mph",
            style: "Clapboard / Dutch Lap",
            colors: "All colors available",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Linen", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Chestnut", tier: "premium", popular: false },
            ],
            description:
              "CertainTeed Mainstreet (.042\") delivers excellent value with a broad color selection and classic profile options for residential siding projects.",
            features: [
              ".042\" vinyl thickness",
              "Clapboard and Dutch Lap profiles",
              "All colors available",
              "Lifetime Limited warranty",
              "Low-maintenance design",
            ],
            idealFor: "Homeowners seeking a mid-range CertainTeed siding at a competitive price.",
          },
          {
            slug: "encore",
            name: "Encore (.040)",
            tagline: "Reliable entry-level siding backed by CertainTeed quality.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/a94bd7255_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "90 mph",
            style: "Clapboard",
            colors: "All colors available",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Linen", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: false },
              { name: "Gray", tier: "standard", popular: true },
            ],
            description:
              "CertainTeed Encore (.040\") is a dependable entry-level vinyl siding option backed by the full CertainTeed warranty program.",
            features: [
              ".040\" vinyl thickness",
              "All colors available",
              "Lifetime Limited warranty",
              "Classic clapboard profile",
            ],
            idealFor: "Budget-conscious projects that still want CertainTeed quality and warranty backing.",
          },
          {
            slug: "american-legend",
            name: "American Legend (.042)",
            tagline: "Rustic cedar shake and shingle aesthetics in low-maintenance vinyl.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/4ab2edfa0_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "100 mph",
            style: "Cedar Impressions / Shake",
            colors: "All colors available",
            colorList: [
              { name: "Weathered Wood", tier: "standard", popular: true },
              { name: "Gray", tier: "standard", popular: false },
              { name: "Charcoal", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: false },
              { name: "Heathered Moss", tier: "premium", popular: false },
            ],
            description:
              "CertainTeed American Legend (.042\") delivers the rustic beauty of cedar shake and shingle in a low-maintenance vinyl panel — ideal for accent gables and full-home applications.",
            features: [
              ".042\" vinyl thickness",
              "Cedar shake / shingle aesthetic",
              "All colors available",
              "Lifetime Limited warranty",
            ],
            idealFor: "Homeowners wanting a cedar shake look with CertainTeed's quality and warranty.",
          },
        ],
      },
    ],
  },

  // ─── GAF ──────────────────────────────────────────────────────────────────
  {
    slug: "gaf",
    name: "GAF",
    tagline: "America's #1 Selling Roofing Brand.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/GAF_Materials_Corporation_logo.svg/320px-GAF_Materials_Corporation_logo.svg.png",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/59972d600_generated_image.png",
    description:
      "GAF is North America's largest roofing manufacturer, producing over 1 billion square feet of roofing material annually. Their products are backed by the industry's strongest warranties.",
    website: "https://www.gaf.com",
    categories: [
      {
        slug: "roofing",
        label: "Roofing",
        description: "GAF's roofing system is built around the Lifetime Roofing System — a complete set of components designed and warranted to work together.",
        products: [
          {
            slug: "timberline-hdz",
            name: "Timberline HDZ",
            tagline: "The #1 selling shingle in America.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/47161b740_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "130 mph",
            style: "Architectural / Laminate",
            colors: "Over 30 colors",
            colorList: [
              { name: "Charcoal", tier: "standard", popular: true, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_charcoal_shingles-opt.png?width=120" },
              { name: "Weathered Wood", tier: "standard", popular: true, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_weathered-wood_shingles-min.png?width=120" },
              { name: "Pewter Gray", tier: "standard", popular: true, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_pewtergray_shingles-min-opt2.png?width=120" },
              { name: "Hickory", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_hickory_shingles-opt.png?width=120" },
              { name: "Slate", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_slate_shingles-min.png?width=120" },
              { name: "Oyster Gray", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_oyster-grey_shingles-min.png?width=120" },
              { name: "Barkwood", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_barkwood_shingle-min.png?width=120" },
              { name: "Shakewood", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_shakewood_shinglesg-min.png?width=120" },
              { name: "Driftwood", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_driftwood_shingles-min.png?width=120" },
              { name: "Hunter Green", tier: "premium", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_hunter-green_shingles-min-opt.png?width=120" },
              { name: "Mission Brown", tier: "premium", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_mission-brown_shingles-min.png?width=120" },
              { name: "Williamsburg Slate", tier: "premium", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_williamsburg-slate_shingles-min.png?width=120" },
            ],
            description:
              "The GAF Timberline HDZ is the best-selling shingle in the United States. With LayerLock™ technology, it achieves a 130 mph wind rating right out of the box.",
            features: [
              "LayerLock™ technology for 130 mph wind warranty standard",
              "StainGuard Plus™ 25-year algae resistance",
              "ASTM D3462 and UL 2218 Class 4 impact resistance",
              "Compatible with GAF Lifetime Roofing System",
              "Class A fire rating",
              "30+ designer color options",
            ],
            idealFor: "Homeowners wanting maximum wind protection with the most trusted name in roofing.",
          },
          {
            slug: "timberline-cs",
            name: "Timberline CS",
            tagline: "Cool Series for energy savings.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/47161b740_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "130 mph",
            style: "Architectural / Cool Roof",
            colors: "10 Energy Star colors",
            colorList: [
              { name: "Charcoal", tier: "standard", popular: true, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_charcoal_shingles-opt.png?width=120" },
              { name: "Pewter Gray", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_pewtergray_shingles-min-opt2.png?width=120" },
              { name: "Hickory", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_hickory_shingles-opt.png?width=120" },
              { name: "Weathered Wood", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_weathered-wood_shingles-min.png?width=120" },
              { name: "Slate", tier: "standard", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_slate_shingles-min.png?width=120" },
              { name: "Mission Brown", tier: "premium", popular: false, swatchUrl: "https://product-assets.gaf.com/media/catalog/product/t/i/timberlinehdz_mission-brown_shingles-min.png?width=120" },
            ],
            description:
              "The Timberline CS (Cool Series) delivers all the performance of the Timberline HDZ with added Energy Star-rated reflective granules that reduce cooling costs in warmer months.",
            features: [
              "Energy Star qualified for reduced cooling loads",
              "LayerLock™ 130 mph wind warranty standard",
              "StainGuard Plus™ algae protection",
              "Lifetime warranty with Lifetime Roofing System",
              "Class A fire rating",
            ],
            idealFor: "Energy-conscious homeowners looking to lower utility bills.",
          },
          {
            slug: "camelot-ii",
            name: "Camelot II",
            tagline: "The look of genuine slate at a fraction of the cost.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/8e66e27cf_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Ultra-Premium / Slate Look",
            colors: "10 premium blends",
            colorList: [
              { name: "Antique Slate", tier: "standard", popular: true },
              { name: "Charcoal", tier: "standard", popular: false },
              { name: "Weathered Fieldstone", tier: "standard", popular: false },
              { name: "Barkwood", tier: "premium", popular: false },
              { name: "Appalachian Sky", tier: "premium", popular: false },
            ],
            description:
              "GAF's Camelot II delivers an extraordinarily realistic slate appearance using advanced layering and shadow technology.",
            features: [
              "Ultra-premium slate-like appearance",
              "StainGuard Plus™ algae resistance",
              "Lifetime Limited Warranty",
              "Class A fire rating",
            ],
            idealFor: "Premium homes or historic neighborhoods requiring a slate-like aesthetic.",
          },
        ],
      },
    ],
  },

  // ─── OWENS CORNING ────────────────────────────────────────────────────────
  {
    slug: "owens-corning",
    name: "Owens Corning",
    tagline: "Built to Last. Backed by Science.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Owens_Corning_logo.svg/320px-Owens_Corning_logo.svg.png",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/330860334_generated_image.png",
    description:
      "Owens Corning is a global leader in roofing, insulation, and composites, with over 80 years of innovation. Their Duration® series shingles are industry benchmarks for performance.",
    website: "https://www.owenscorning.com",
    categories: [
      {
        slug: "roofing",
        label: "Roofing",
        description: "Owens Corning's roofing systems center around the TruDefinition® technology platform, delivering sharp contrast and color consistency.",
        products: [
          {
            slug: "duration",
            name: "Duration® Series",
            tagline: "SureNail® technology for unmatched wind resistance.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/ee580ee44_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "130 mph",
            style: "Architectural / Laminate",
            colors: "Over 40 colors",
            colorList: [
              { name: "Onyx Black", tier: "standard", popular: true },
              { name: "Estate Gray", tier: "standard", popular: true },
              { name: "Driftwood", tier: "standard", popular: true },
              { name: "Quarry Gray", tier: "standard", popular: false },
              { name: "Aged Oak", tier: "standard", popular: false },
              { name: "Sierra Gray", tier: "standard", popular: false },
              { name: "Brownwood", tier: "standard", popular: false },
              { name: "Teak", tier: "standard", popular: false },
              { name: "Sedona", tier: "premium", popular: false },
              { name: "Pacific Wave", tier: "premium", popular: false },
            ],
            description:
              "The Duration® shingle features SureNail® Technology — a unique fabric strip in the nailing zone that provides three times the grip of standard shingles.",
            features: [
              "SureNail® Technology for 3x nail grip",
              "130 mph wind warranty",
              "TruDefinition® color technology",
              "StreakGuard™ algae resistance",
              "Lifetime Limited warranty",
              "Class A fire rating",
            ],
            idealFor: "Homeowners in wind-prone areas wanting maximum uplift resistance.",
          },
          {
            slug: "oakridge",
            name: "Oakridge®",
            tagline: "Great looks. Proven performance. Smart value.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/b9b440b36_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "110 mph",
            style: "Architectural",
            colors: "Over 25 colors",
            colorList: [
              { name: "Onyx Black", tier: "standard", popular: true },
              { name: "Estate Gray", tier: "standard", popular: true },
              { name: "Driftwood", tier: "standard", popular: true },
              { name: "Quarry Gray", tier: "standard", popular: false },
              { name: "Aged Oak", tier: "standard", popular: false },
              { name: "Sierra Gray", tier: "standard", popular: false },
              { name: "Brownwood", tier: "standard", popular: false },
              { name: "Sedona", tier: "premium", popular: false },
            ],
            description:
              "The Oakridge® shingle delivers TruDefinition® beauty and solid performance at a more accessible price point.",
            features: [
              "TruDefinition® color technology",
              "110 mph wind warranty",
              "StreakGuard™ algae resistance",
              "Lifetime Limited warranty",
              "Class A fire rating",
            ],
            idealFor: "Budget-conscious homeowners who don't want to sacrifice quality or appearance.",
          },
        ],
      },
    ],
  },

  // ─── IKO ──────────────────────────────────────────────────────────────────
  {
    slug: "iko",
    name: "IKO",
    tagline: "The Foundation of a Great Roof.",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/IKO_logo.svg/320px-IKO_logo.svg.png",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/bf63f9fa5_generated_image.png",
    description:
      "IKO is a global roofing manufacturer with over 70 years of experience. Their Cambridge and Dynasty lines are popular throughout Ohio for their value and performance.",
    website: "https://www.iko.com",
    categories: [
      {
        slug: "roofing",
        label: "Roofing",
        description: "IKO's architectural shingle lines combine value-driven pricing with performance features that meet the demands of Northeast Ohio weather.",
        products: [
          {
            slug: "cambridge",
            name: "Cambridge",
            tagline: "Reliable performance at an accessible price.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/55bf3c285_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Architectural / Laminate",
            colors: "Over 20 colors",
            colorList: [
              { name: "Charcoal Gray", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/CHGY_IKO_CRC_CAMB_SWCH-upd-min.webp" },
              { name: "Weathered Wood", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-WTWD_IKO_CRC_CAMB_SWCH-upd-min.webp" },
              { name: "Dual Gray", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/2048_IKO_CRC_CAMB_SWCH_DGRY-min.webp" },
              { name: "Dual Black", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/2048_IKO_CRC_CAMB_SWCH_DBLK.webp" },
              { name: "Driftwood", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/IKO_Cambridge_Driftwood.webp" },
              { name: "Dual Brown", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/2048_IKO_CRC_CAMB_SWCH_DBWN-min.webp" },
              { name: "Earthtone Cedar", tier: "premium", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-ETC_IKO_CRC_CAMB_SWCH-upd-min.webp" },
              { name: "Harvard Slate", tier: "premium", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/2048_IKO_CRC_CAMB_SWCH_HRVD_SLTE-min.webp" },
            ],
            description:
              "The IKO Cambridge shingle is one of the most popular value-tier architectural shingles in the market. Its enhanced laminate construction provides excellent dimensional appearance.",
            features: [
              "ArmourZone™ reinforced nailing area",
              "Blue CORE™ fiberglass mat",
              "Scotchgard™ Protector for algae resistance",
              "110 mph wind resistance",
              "Lifetime Limited warranty",
              "Class A fire rating",
            ],
            idealFor: "Budget-focused projects without compromising on dimensional appearance.",
          },
          {
            slug: "dynasty",
            name: "Dynasty®",
            tagline: "Premium wind protection. Proven reliability.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/2e1132e2a_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "130 mph",
            style: "Architectural / Enhanced",
            colors: "Over 25 colors",
            colorList: [
              { name: "Olde Style Weatherwood", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2025/11/1400_OLDE_STYL_WTWD_DYST_SWCH-e1776783852639.webp" },
              { name: "Granite Black", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/04/RGB-GRBK_IKO_CRC_PRFM_SWCH-upd-min.webp" },
              { name: "Cornerstone Weatherwood", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-CRNS_IKO_CRC_PRFM_SWCH-upd-min-1.webp" },
              { name: "Shadow Brown", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/04/RGB-SHBN_IKO_CRC_PRFM_SWCH.webp" },
              { name: "Summit Grey", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-SUMT_GREY_IKO_CRC_DYST_SWCH.webp" },
              { name: "Frostone Grey", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/FRGY_IKO_CRC_PRFM_SWCH-1.webp" },
              { name: "Atlantic Blue", tier: "premium", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/12/RGB-ATBL_IKO_CRC_DYST_SWCH-upd-min.webp" },
              { name: "Glacier", tier: "premium", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/04/RGB-GLCR_IKO_CRC_PRFM_SWCH-upd-min.webp" },
              { name: "Brownstone", tier: "premium", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-BSTN_IKO_CRC_PRFM_SWCH-upd-min-1.webp" },
              { name: "Emerald Green", tier: "premium", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-EMGR_IKO_CRC_DYST_SWCH-upd-min.webp" },
            ],
            description:
              "The IKO Dynasty shingle steps up with a 130 mph wind warranty, ArmourZone™ reinforced nailing, and Fastlock® dual-compound sealant.",
            features: [
              "130 mph wind warranty",
              "ArmourZone™ reinforced nailing area",
              "Fastlock® dual-compound sealant",
              "Blue CORE™ fiberglass mat",
              "Scotchgard™ algae resistance",
              "Lifetime Limited warranty",
              "Class A fire rating",
            ],
            idealFor: "Homeowners wanting upgraded wind performance without the luxury price tag.",
          },
          {
            slug: "marathon",
            name: "Marathon",
            tagline: "Proven 3-tab performance for straightforward reroofing.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/b87a19933_generated_image.png",
            warranty: "25-Year Limited",
            windRating: "60 mph",
            style: "3-Tab",
            colors: "12 colors",
            colorList: [
              { name: "Charcoal Gray", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/CHGY_IKO_CRC_CAMB_SWCH-upd-min.webp" },
              { name: "Weathered Wood", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-WTWD_IKO_CRC_CAMB_SWCH-upd-min.webp" },
              { name: "Dual Brown", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/2048_IKO_CRC_CAMB_SWCH_DBWN-min.webp" },
            ],
            description:
              "The IKO Marathon is a classic 3-tab shingle offering reliable, budget-friendly roofing for straightforward reroofing projects.",
            features: [
              "3-tab profile for a clean, uniform look",
              "25-Year Limited warranty",
              "Algae-resistance option",
              "Class A fire rating",
            ],
            idealFor: "Straightforward reroofing projects where cost is the primary consideration.",
          },
          {
            slug: "leading-edge",
            name: "Leading Edge Plus",
            tagline: "Value-priced starter and low-slope shingle.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/b87a19933_generated_image.png",
            warranty: "25-Year Limited",
            windRating: "60 mph",
            style: "3-Tab / Starter",
            colors: "6 colors",
            colorList: [
              { name: "Charcoal Gray", tier: "standard", popular: true, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/CHGY_IKO_CRC_CAMB_SWCH-upd-min.webp" },
              { name: "Weathered Wood", tier: "standard", popular: false, swatchUrl: "https://www.iko.com/na/wp-content/uploads/2024/05/RGB-WTWD_IKO_CRC_CAMB_SWCH-upd-min.webp" },
            ],
            description:
              "IKO Leading Edge Plus is a versatile 3-tab shingle often used as a starter strip and in lower-slope applications.",
            features: [
              "Versatile starter / low-slope application",
              "25-Year Limited warranty",
              "Class A fire rating",
            ],
            idealFor: "Starter strip applications and low-slope roofing.",
          },
        ],
      },
    ],
  },

  // ─── PROVIA ───────────────────────────────────────────────────────────────
  {
    slug: "provia",
    name: "ProVia",
    tagline: "Uncompromising Quality. Extraordinary Results.",
    logo: "https://www.provia.com/wp-content/uploads/2022/08/ProVia-Logo.png",
    heroImage: "https://www.provia.com/wp-content/uploads/2023/12/CedarMAX-D6-Granite-1.jpg",
    description:
      "ProVia is an Ohio-based manufacturer known for handcrafting premium entry doors, siding, and windows with an obsessive attention to detail. Their siding, window, and door lines are a cut above the mass-market options — built for performance, beauty, and longevity.",
    website: "https://www.provia.com",
    categories: [
      {
        slug: "siding",
        label: "Siding",
        description: "ProVia offers six distinct vinyl siding lines — from premium insulated systems to budget-friendly options — all manufactured with Super Polymer technology.",
        products: [
          {
            slug: "cedarmax",
            name: "CedarMAX® (.050/.046)",
            tagline: "Premium insulated vinyl siding for maximum energy performance.",
            image: "https://www.provia.com/wp-content/uploads/2023/12/CedarMAX-D6-Granite-1.jpg",
            warranty: "Lifetime Limited",
            windRating: "Varies by profile",
            style: "Insulated / Single 7\", Double 6\" Clapboard, Triple 4\" Dutch Lap, Board & Batten",
            colors: "40+ colors",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Linen", tier: "standard", popular: true },
              { name: "Antique White", tier: "standard", popular: true },
              { name: "Cream", tier: "standard", popular: false },
              { name: "Alabaster", tier: "standard", popular: false },
              { name: "Sandalwood", tier: "standard", popular: true },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Pewter", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Granite", tier: "standard", popular: true },
              { name: "Timberline", tier: "standard", popular: false },
              { name: "Premium Blue", tier: "premium", popular: false },
              { name: "Sage", tier: "premium", popular: false },
              { name: "Sea Slate", tier: "premium", popular: true },
              { name: "Nightfall", tier: "premium", popular: false },
              { name: "Myst Gray", tier: "premium", popular: true },
              { name: "Harvest Red", tier: "premium", popular: false },
              { name: "Coal Black", tier: "premium", popular: true },
            ],
            description:
              "CedarMAX® is ProVia's top-of-the-line insulated vinyl siding, featuring a rigid EPS foam backing permanently laminated to the panel.",
            features: [
              "Rigid EPS foam insulation permanently laminated to panel",
              ".046\" and .050\" vinyl thickness options",
              "4 profile options",
              "5x greater impact resistance vs. non-insulated siding",
              "Chromatix™ technology on dark/premium colors",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners prioritizing energy efficiency alongside premium aesthetics.",
          },
          {
            slug: "cedar-peaks",
            name: "Cedar Peaks® (.046/.048)",
            tagline: "Premium non-insulated vinyl with outstanding thickness and texture.",
            image: "https://www.provia.com/wp-content/uploads/2023/12/Cedar-Peaks-D4-5-DL-Gray-1.jpg",
            warranty: "Lifetime Limited",
            windRating: "Varies by profile",
            style: "Non-Insulated / D4, D4.5 Dutch Lap, Board & Batten, Vertical",
            colors: "40+ colors",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Linen", tier: "standard", popular: true },
              { name: "Sandalwood", tier: "standard", popular: true },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Granite", tier: "standard", popular: false },
              { name: "Timberline", tier: "standard", popular: false },
              { name: "Premium Blue", tier: "premium", popular: false },
              { name: "Sea Slate", tier: "premium", popular: false },
              { name: "Myst Gray", tier: "premium", popular: true },
              { name: "Coal Black", tier: "premium", popular: true },
              { name: "Harvest Red", tier: "premium", popular: false },
            ],
            description:
              "Cedar Peaks® is ProVia's flagship non-insulated siding line, available in .046\" and .050\" vinyl thickness.",
            features: [
              ".046\" and .050\" vinyl thickness options",
              "4 profile options",
              "Authentic cedar woodgrain embossing",
              "Tri-Pigment Reflective Technology",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners wanting ProVia's thickest non-insulated panel.",
          },
          {
            slug: "hearttech",
            name: "HeartTech® (.044)",
            tagline: "Oak woodgrain character. Four versatile profile options.",
            image: "https://www.provia.com/wp-content/uploads/2023/12/HeartTech-Gray-750x750.jpg",
            warranty: "Lifetime Limited",
            windRating: "Varies by profile",
            style: "Non-Insulated / D4, D5, Dutch Lap, Vertical",
            colors: "30+ colors",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Linen", tier: "standard", popular: true },
              { name: "Sandalwood", tier: "standard", popular: true },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Granite", tier: "standard", popular: false },
              { name: "Premium Blue", tier: "premium", popular: false },
              { name: "Sea Slate", tier: "premium", popular: false },
              { name: "Myst Gray", tier: "premium", popular: false },
              { name: "Coal Black", tier: "premium", popular: false },
            ],
            description:
              "HeartTech® features a distinctive oak woodgrain texture — ProVia's #1 selling siding for nearly 30 years.",
            features: [
              ".044\" vinyl thickness",
              "Realistic oak woodgrain texture",
              "4 profile options",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners wanting an oak-textured, mid-range premium siding.",
          },
          {
            slug: "willowbrook",
            name: "Willowbrook™ (.042)",
            tagline: "The most versatile profile selection in the ProVia lineup.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/6cccec395_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "Varies by profile",
            style: "Non-Insulated / 6 Profile Options",
            colors: "30+ colors",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Linen", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: false },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Sea Slate", tier: "premium", popular: false },
              { name: "Coal Black", tier: "premium", popular: false },
              { name: "Myst Gray", tier: "premium", popular: false },
            ],
            description:
              "Willowbrook™ offers more profile variety than any other ProVia siding line — six options including Double 4\", Double 5\", Dutch Lap, Beaded, Board & Batten, and Vertical.",
            features: [
              ".042\" vinyl thickness",
              "6 profile options — the most in the ProVia lineup",
              "Profiles include beaded seam and board & batten",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners who need maximum profile flexibility.",
          },
          {
            slug: "ultra",
            name: "Ultra™ (.040)",
            tagline: "Reliable performance. Budget-friendly price.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/9e0c5d8c9_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "Varies by profile",
            style: "Non-Insulated / D4, D5, Dutch Lap",
            colors: "25+ colors",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Clay", tier: "standard", popular: false },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Granite", tier: "standard", popular: false },
              { name: "Sea Slate", tier: "premium", popular: false },
              { name: "Coal Black", tier: "premium", popular: false },
            ],
            description:
              "ProVia's Ultra™ is the entry-level line but still manufactured with the Super Polymer formulation that sets ProVia apart from mass-market brands.",
            features: [
              ".040\" vinyl thickness",
              "3 profile options",
              "Super Polymer formulation",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Budget-conscious homeowners who still want a ProVia-quality product.",
          },
          {
            slug: "harbor-mill",
            name: "Harbor Mill™ Shake & Shingle",
            tagline: "Ultra-realistic cedar shake — in low-maintenance polypropylene.",
            image: "https://www.provia.com/wp-content/uploads/2023/12/Harbor-Mill-Myst-Gray-2025-brand-tile-revised-1.jpg",
            warranty: "Lifetime Limited",
            windRating: "Varies by profile",
            style: "Shake / Shingle Accent Panel",
            colors: "27+ colors",
            colorList: [
              { name: "Sandalwood", tier: "standard", popular: true },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Canyon", tier: "standard", popular: true },
              { name: "Timberline", tier: "standard", popular: true },
              { name: "Myst Gray", tier: "premium", popular: true },
              { name: "Coal Black", tier: "premium", popular: true },
              { name: "Sea Slate", tier: "premium", popular: false },
            ],
            description:
              "Harbor Mill™ is ProVia's premium shake and shingle panel line, crafted from low-maintenance polypropylene for greater rigidity and dimensional stability.",
            features: [
              "Low-maintenance polypropylene construction",
              "Two profiles: Single 7\" Rough-Sawn Shingle & Single 8\" Staggered Hand-Split Shake",
              "Ultra-realistic cedar texture",
              "100% recyclable",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners adding architectural interest to gable ends, dormers, or accent areas.",
          },
        ],
      },
      {
        slug: "windows",
        label: "Windows",
        description: "ProVia manufactures premium vinyl and fiberglass replacement windows built for Northeast Ohio's climate demands.",
        products: [
          {
            slug: "endure",
            name: "Endure™ Windows",
            tagline: "High-performance vinyl windows engineered for energy savings.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/9b70b77df_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "Design Pressure Rated",
            style: "Double Hung, Casement, Awning, Slider, Picture",
            colors: "Interior and exterior color options",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Bronze", tier: "premium", popular: false },
              { name: "Slate Gray", tier: "premium", popular: true },
              { name: "Black", tier: "premium", popular: true },
            ],
            description:
              "ProVia Endure™ windows are premium vinyl replacement windows featuring multi-chambered frames, Low-E glass, and argon gas fills for superior energy performance.",
            features: [
              "Multi-chambered vinyl frame for maximum insulation",
              "Low-E glass with argon gas fill standard",
              "Energy Star certified",
              "Multiple operating styles available",
              "Lifetime Limited Warranty",
              "Made in the USA",
            ],
            idealFor: "Homeowners looking for premium replacement windows with outstanding energy performance.",
          },
          {
            slug: "aeris",
            name: "Aeris™ Fiberglass Windows",
            tagline: "Stronger than vinyl. More beautiful than aluminum.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/4fc83c820_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "High Design Pressure Rated",
            style: "Double Hung, Casement, Awning, Bay, Bow",
            colors: "Interior wood grain options available",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Tan", tier: "standard", popular: false },
              { name: "Bronze", tier: "premium", popular: false },
              { name: "Dark Bronze", tier: "premium", popular: false },
              { name: "Slate", tier: "premium", popular: true },
              { name: "Black", tier: "premium", popular: true },
            ],
            description:
              "ProVia Aeris™ fiberglass windows offer unmatched strength, exceptional thermal performance, and wood-like aesthetics without the maintenance.",
            features: [
              "Fiberglass construction — 8x stronger than vinyl",
              "Minimal expansion/contraction in temperature extremes",
              "Interior wood-grain finish options",
              "Energy Star certified",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners wanting the premium look of wood with the durability and performance of fiberglass.",
          },
        ],
      },
      {
        slug: "doors",
        label: "Entry Doors",
        description: "ProVia handcrafts premium fiberglass and steel entry door systems built with exceptional fit, finish, and energy performance.",
        products: [
          {
            slug: "embarq",
            name: "Embarq™ Fiberglass Door",
            tagline: "Fiberglass doors made for performance and presence.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/3abc59c7e_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "N/A — door system",
            style: "Smooth / Woodgrain Textured Fiberglass",
            colors: "Fully paintable or factory finished",
            colorList: [
              { name: "Primed (paintable)", tier: "standard", popular: true },
              { name: "Classic White", tier: "standard", popular: false },
              { name: "Factory stained woodgrain", tier: "premium", popular: false },
            ],
            description:
              "The ProVia Embarq™ fiberglass entry door is handcrafted in Ohio with precision joints, multi-chamber foam core, and triple weatherstripping.",
            features: [
              "Multi-chamber polyurethane foam core",
              "Triple weatherstripping",
              "ENERGY STAR certified",
              "Fully customizable glass lites",
              "Handcrafted in Ohio",
              "Lifetime warranty on door slab",
            ],
            idealFor: "Homeowners upgrading entry doors for energy efficiency, security, and curb appeal.",
          },
          {
            slug: "heritage",
            name: "Heritage™ Steel Door",
            tagline: "Heavy-gauge steel security meets stunning curb appeal.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/e096f10fb_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "N/A — door system",
            style: "Steel / Woodgrain Embossed",
            colors: "Factory painted or field paintable",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Red", tier: "standard", popular: false },
              { name: "Black", tier: "premium", popular: true },
              { name: "Walnut (woodgrain)", tier: "premium", popular: false },
            ],
            description:
              "ProVia Heritage™ steel doors offer security, durability, and design flexibility with polyurethane foam core insulation and realistic woodgrain embossing.",
            features: [
              "Heavy-gauge steel construction",
              "Polyurethane foam core insulation",
              "Realistic woodgrain embossing",
              "ENERGY STAR certified",
              "Triple weatherstripping",
              "Lifetime warranty",
            ],
            idealFor: "Homeowners wanting maximum security with attractive curb appeal.",
          },
        ],
      },
    ],
  },

  // ─── GERKIN WINDOWS & DOORS ───────────────────────────────────────────────
  {
    slug: "gerkin",
    name: "Gerkin Windows & Doors",
    tagline: "Built for Performance. Made in America.",
    logo: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=320&q=80",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/6bcbfd9be_generated_image.png",
    description:
      "Gerkin Windows & Doors is an American manufacturer producing high-performance vinyl windows and doors from their facility in South Sioux City, Nebraska. Known for energy efficiency, customization options, and strength, Gerkin is a trusted choice for Northeast Ohio replacement projects.",
    website: "https://www.gerkin.com",
    categories: [
      {
        slug: "windows",
        label: "Windows",
        description: "Gerkin offers a full range of vinyl replacement and new construction windows built to exceed Energy Star requirements.",
        products: [
          {
            slug: "series-900",
            name: "Series 900 Double Hung",
            tagline: "Premium performance double-hung vinyl window.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/6bcbfd9be_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "Design Pressure Rated",
            style: "Double Hung",
            colors: "Multiple exterior colors available",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Tan", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Bronze", tier: "premium", popular: false },
              { name: "Slate Gray", tier: "premium", popular: true },
              { name: "Black", tier: "premium", popular: true },
            ],
            description:
              "The Gerkin Series 900 is their flagship double-hung vinyl window featuring multi-chambered sash and frame, Low-E glass, and argon fill for superior energy performance in Northeast Ohio climates.",
            features: [
              "Multi-chambered vinyl frame and sash",
              "Low-E glass with argon gas fill",
              "Energy Star certified",
              "Tilt-in sash for easy cleaning",
              "Fusion-welded frame corners",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners replacing existing double-hung windows for better energy performance.",
          },
          {
            slug: "casement-awning",
            name: "Casement & Awning Windows",
            tagline: "Crank-operated ventilation with a tight weather seal.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/00f160cd7_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "Design Pressure Rated",
            style: "Casement / Awning",
            colors: "Multiple colors available",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Slate Gray", tier: "premium", popular: true },
              { name: "Black", tier: "premium", popular: true },
            ],
            description:
              "Gerkin casement and awning windows provide excellent ventilation with a crank-operated sash that creates a watertight compression seal when closed.",
            features: [
              "Crank-operated multi-point lock system",
              "Compression seal for maximum weather resistance",
              "Low-E glass with argon fill",
              "Energy Star certified",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners wanting maximum ventilation control and weather tightness.",
          },
        ],
      },
      {
        slug: "doors",
        label: "Doors",
        description: "Gerkin manufactures premium sliding patio doors and entry systems built for performance.",
        products: [
          {
            slug: "sliding-patio",
            name: "Sliding Patio Door",
            tagline: "Smooth-gliding patio access with superior energy performance.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/16baa667b_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "Design Pressure Rated",
            style: "Sliding Patio Door",
            colors: "White, Almond, Clay, Bronze, Black",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Clay", tier: "standard", popular: false },
              { name: "Bronze", tier: "premium", popular: false },
              { name: "Black", tier: "premium", popular: true },
            ],
            description:
              "Gerkin's vinyl sliding patio doors combine smooth operation, multi-point locking, and energy-efficient glass for a durable patio access solution.",
            features: [
              "Multi-chambered vinyl frame",
              "Multi-point locking hardware",
              "Low-E glass with argon fill",
              "Energy Star certified",
              "Lifetime Limited Warranty",
            ],
            idealFor: "Homeowners replacing aging patio doors for improved security and energy performance.",
          },
        ],
      },
    ],
  },

  // ─── LARSON ───────────────────────────────────────────────────────────────
  {
    slug: "larson",
    name: "Larson",
    tagline: "America's #1 Storm & Screen Door Brand.",
    logo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=320&q=80",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/7b907ef01_generated_image.png",
    description:
      "Larson is the leading brand in storm doors, screen doors, and security doors in North America. Their doors are designed to add an extra layer of protection, ventilation, and energy efficiency to any entry.",
    website: "https://www.larsondoors.com",
    categories: [
      {
        slug: "doors",
        label: "Storm & Screen Doors",
        description: "Larson offers a wide range of storm doors, full-view doors, and retractable screen doors for every home style and budget.",
        products: [
          {
            slug: "tradewinds",
            name: "Tradewinds Select",
            tagline: "Classic storm door protection with full-view glass.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/7b907ef01_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "N/A — storm door",
            style: "Full-View Storm Door",
            colors: "White, Almond, Brown, Black",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Brown", tier: "standard", popular: false },
              { name: "Black", tier: "premium", popular: true },
            ],
            description:
              "The Larson Tradewinds Select is a full-view aluminum storm door with interchangeable glass and screen panels, providing year-round protection and ventilation.",
            features: [
              "Heavy-duty aluminum frame",
              "Interchangeable glass & screen panels",
              "Available in multiple sizes",
              "Easy installation",
              "Limited Lifetime Warranty",
            ],
            idealFor: "Homeowners adding storm door protection to existing entry doors.",
          },
          {
            slug: "secure-elegance",
            name: "Secure Elegance",
            tagline: "Decorative security storm door with reinforced frame.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/43fde73a2_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "N/A — storm door",
            style: "Security Storm Door",
            colors: "White, Almond, Brown, Black",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Brown", tier: "standard", popular: false },
              { name: "Black", tier: "premium", popular: true },
              { name: "Almond", tier: "standard", popular: false },
            ],
            description:
              "Larson Secure Elegance combines decorative styling with a reinforced aluminum frame for added security without sacrificing appearance.",
            features: [
              "Reinforced aluminum frame for security",
              "Decorative glass options",
              "Multi-point locking available",
              "Limited Lifetime Warranty",
            ],
            idealFor: "Homeowners wanting the look of an attractive door with added security.",
          },
        ],
      },
    ],
  },

  // ─── THERMA-TRU ───────────────────────────────────────────────────────────
  {
    slug: "therma-tru",
    name: "Therma-Tru",
    tagline: "America's #1 Fiberglass & Steel Entry Door Brand.",
    logo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=320&q=80",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/75092fc19_generated_image.png",
    description:
      "Therma-Tru is the nation's leading manufacturer of fiberglass and steel entry door systems. Their doors offer the warmth and beauty of wood with dramatically better energy efficiency, security, and durability.",
    website: "https://www.thermatru.com",
    categories: [
      {
        slug: "doors",
        label: "Entry Doors",
        description: "Therma-Tru's Fiber-Classic® and Smooth-Star® lines deliver stunning curb appeal with industry-leading energy performance.",
        products: [
          {
            slug: "fiber-classic",
            name: "Fiber-Classic® Oak",
            tagline: "Authentic oak woodgrain fiberglass for a timeless entry.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/75092fc19_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "N/A — door system",
            style: "Fiberglass / Oak Woodgrain",
            colors: "Stainable or paintable",
            colorList: [
              { name: "Stainable (unfinished)", tier: "standard", popular: true },
              { name: "Pre-stained light oak", tier: "standard", popular: false },
              { name: "Pre-stained dark walnut", tier: "premium", popular: false },
              { name: "Pre-painted white", tier: "standard", popular: false },
              { name: "Pre-painted black", tier: "premium", popular: true },
            ],
            description:
              "The Therma-Tru Fiber-Classic® Oak replicates the look of authentic oak woodgrain in a fiberglass panel that won't warp, crack, or require painting.",
            features: [
              "Authentic oak woodgrain texture",
              "Stainable like real wood",
              "Polyurethane foam core for energy efficiency",
              "ENERGY STAR certified",
              "Triple weatherstripping",
              "Limited Lifetime Warranty",
            ],
            idealFor: "Homeowners wanting the look of a stained wood entry door with zero maintenance.",
          },
          {
            slug: "smooth-star",
            name: "Smooth-Star®",
            tagline: "Smooth fiberglass — the perfect canvas for any paint color.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/d11d80dc4_generated_image.png",
            warranty: "Limited Lifetime",
            windRating: "N/A — door system",
            style: "Fiberglass / Smooth",
            colors: "Paintable to any color",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Black", tier: "premium", popular: true },
              { name: "Red", tier: "standard", popular: false },
              { name: "Navy Blue", tier: "premium", popular: false },
              { name: "Forest Green", tier: "premium", popular: false },
              { name: "Custom color (field painted)", tier: "premium", popular: false },
            ],
            description:
              "The Therma-Tru Smooth-Star® features a smooth fiberglass surface that accepts paint like wood — ideal for any color scheme, especially bold front door statements.",
            features: [
              "Smooth fiberglass — paintable to any color",
              "Polyurethane foam core",
              "ENERGY STAR certified",
              "Wide glass and panel design options",
              "Limited Lifetime Warranty",
            ],
            idealFor: "Homeowners who want to make a bold front door statement with a custom paint color.",
          },
        ],
      },
    ],
  },

  // ─── GENTEK / ASSOCIATED MATERIALS ───────────────────────────────────────
  {
    slug: "gentek",
    name: "Gentek / Associated Materials",
    tagline: "Professional-Grade Siding & Accessories.",
    logo: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=320&q=80",
    heroImage: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/53e50a0af_generated_image.png",
    description:
      "Gentek, a brand of Associated Materials, is a North American manufacturer of professional-grade vinyl siding, soffit, and accessories. Their Signature Supreme line is a top choice for contractors across Northeast Ohio.",
    website: "https://www.associatedmaterials.com",
    categories: [
      {
        slug: "siding",
        label: "Siding",
        description: "Gentek siding products are engineered for the contractor — consistent quality, great color selection, and strong performance.",
        products: [
          {
            slug: "signature-supreme",
            name: "Signature Supreme (.044)",
            tagline: "Professional contractor-grade vinyl siding.",
            image: "https://media.base44.com/images/public/6a22e139a45d8195801a1ea3/53e50a0af_generated_image.png",
            warranty: "Lifetime Limited",
            windRating: "110 mph",
            style: "Double 4\" / Double 4.5\" Clapboard / Dutch Lap",
            colors: "All colors available",
            colorList: [
              { name: "White", tier: "standard", popular: true },
              { name: "Almond", tier: "standard", popular: false },
              { name: "Linen", tier: "standard", popular: true },
              { name: "Clay", tier: "standard", popular: true },
              { name: "Gray", tier: "standard", popular: true },
              { name: "Beige", tier: "standard", popular: false },
              { name: "Heather", tier: "standard", popular: false },
              { name: "Autumn Red", tier: "premium", popular: false },
              { name: "Forest Green", tier: "premium", popular: false },
              { name: "Midnight Blue", tier: "premium", popular: false },
            ],
            description:
              "Gentek Signature Supreme (.044\") is the flagship professional contractor vinyl siding product from Associated Materials — a consistent, reliable panel trusted by roofers and siding contractors throughout Northeast Ohio.",
            features: [
              ".044\" vinyl thickness",
              "Double 4\" and Double 4.5\" profiles",
              "All colors available",
              "Lifetime Limited warranty",
              "110 mph wind resistance",
              "WeatherBlock™ technology",
            ],
            idealFor: "Contractors and homeowners needing a reliable, professional-grade vinyl siding with strong regional availability.",
          },
        ],
      },
    ],
  },
];

export function findManufacturer(slug) {
  return MANUFACTURERS.find(m => m.slug === slug) || null;
}

export function findCategory(manufacturer, categorySlug) {
  return manufacturer?.categories.find(c => c.slug === categorySlug) || null;
}

export function findProduct(category, productSlug) {
  return category?.products.find(p => p.slug === productSlug) || null;
}