import React,{useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {base44} from "@/api/base44Client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ContactSection from "@/components/ContactSection";
import useSEO from "@/hooks/useSEO";
function Notice({item}){
 const active=Date.parse(item.expires_at)>Date.now();
 return <><p className="text-sm font-semibold text-primary">{active?"Weather warning":"Past weather notice — warning expired"}</p><h1 className="text-3xl md:text-5xl font-heading font-bold my-5">{item.title}</h1><p className="text-lg mb-4">{item.summary}</p><p className="text-sm text-muted-foreground">Issued {new Date(item.issued_at).toLocaleString("en-US",{timeZone:"America/New_York"})} Eastern · Expires {new Date(item.expires_at).toLocaleString("en-US",{timeZone:"America/New_York"})} Eastern</p><a className="inline-block underline text-primary my-4" href={item.source_url} target="_blank" rel="noopener noreferrer">Read the original National Weather Service alert</a><h2 className="text-2xl font-bold mt-8 mb-3">Official safety instructions</h2><p className="whitespace-pre-line text-muted-foreground">{item.instruction}</p><h2 className="text-2xl font-bold mt-8 mb-3">What to check once conditions are safe</h2><p>Look from the ground for missing shingles, displaced siding, dented gutters and debris. Photograph visible changes with the date and location. Stay off the roof, avoid downed lines, and call emergency services for immediate danger.</p><h2 className="text-2xl font-bold mt-8 mb-3">Preparing an insurance claim</h2><p>Save photos, receipts for temporary protection, your policy number and the date you first noticed damage. Contact your insurer to ask about reporting requirements and deadlines. An inspection can document the condition of your property; the insurer determines coverage.</p><div className="flex flex-wrap gap-4 mt-6"><Link className="underline text-primary" to="/insurance-claims/help">Read claim questions and answers</Link><a className="underline text-primary" href="#contact">Request an inspection visit</a></div></>;
}
export default function StormUpdates(){
 const {slug}=useParams(); const [items,setItems]=useState([]);const [status,setStatus]=useState("loading");
 useSEO({title:slug&&items[0]?items[0].title+" | Demore Exterior Solutions":"Local Storm Updates | Demore Exterior Solutions",description:slug&&items[0]?items[0].summary:"Official weather notices and practical next steps for Northeast Ohio homeowners.",canonical:slug?"/storm-updates/"+slug:"/storm-updates"});
 useEffect(()=>{let live=true;setStatus("loading");base44.entities.StormNotice.filter({status:"published",...(slug?{slug}:{})},"-issued_at",100).then(rows=>{if(live){setItems(rows);setStatus("ready");}}).catch(()=>{if(live)setStatus("error");});return()=>{live=false;};},[slug]);
 return <div className="min-h-screen bg-background"><Navbar/><main className="max-w-4xl mx-auto px-4 pt-32 pb-16">{status==="loading"?<p role="status">Loading weather notices…</p>:status==="error"?<p role="alert">Weather notices could not load. <a className="underline" href="https://www.weather.gov/cle/">Check NWS Cleveland</a> for current information.</p>:slug?(items[0]?<Notice item={items[0]}/>:<><h1 className="text-3xl font-bold">Notice not found</h1><Link to="/storm-updates">All storm updates</Link></>):<><h1 className="text-4xl font-heading font-bold mb-4">Local storm updates</h1><p className="text-muted-foreground mb-8">National Weather Service warnings for our Northeast Ohio service counties. Warnings describe weather risk; they do not establish damage or insurance coverage at an individual home.</p>{items.length?items.map(n=><article key={n.id} className="border rounded-xl p-6 mb-4"><p className="text-sm text-muted-foreground">{Date.parse(n.expires_at)>Date.now()?"Warning":"Past notice"}</p><h2 className="text-xl font-bold"><Link className="text-primary underline" to={"/storm-updates/"+n.slug}>{n.title}</Link></h2></article>):<p>No storm notices have been posted yet. <a className="underline text-primary" href="https://www.weather.gov/cle/">Check current conditions with NWS Cleveland.</a></p>}</>}</main>{slug&&items[0]&&<ContactSection mode="inspection"/>}<Footer/></div>;
}